sudo: required

dist: trusty

osx_image: xcode7.3

os:
  - linux
  - osx

language: node_js

node_js:
  - 7
  - node

branches:
  only: master

install: npm install

script: npm run test-cov

after_success: npm run send-cov

notifications:
  email:
    on_success: never
