version: '3'

services:
  tribeca:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: ./
    image: tribeca
    env_file:
      - ./.env
    tty: true
    restart: unless-stopped
    volumes:
        - ${LOCAL_DB_DIR}:/data/db
#    links:
#      - tribeca-mongo
#    depends_on:
#        - tribeca-mongo
#  tribeca-mongo:
#    container_name: ${DB_CONTAINER_NAME}
#    image: mongo
#    restart: unless-stopped
#    volumes:
#        - ${LOCAL_DB_DIR}:/data/db
#     environment:
#       MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

networks:
    default:
       external:
        name: ${NETWORK}
